//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Foundational Module" recipe.
//
// The LayoutView usercontrol defines a layout decoupled from the shell. 
// It provides a left and right workspace, menu bar, tool bar and status bar.
// These ui elements are added as extension sites.
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-030-How_to_Create_a_Foundational_Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.AboutModule
{
    partial class LayoutView
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.mailtoLink = new System.Windows.Forms.LinkLabel();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.site2Link = new System.Windows.Forms.LinkLabel();
            this.siteLink = new System.Windows.Forms.LinkLabel();
            this.seeLicenseLinkLabel = new System.Windows.Forms.LinkLabel();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.versionLabel = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.developerLabel1 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // mailtoLink
            // 
            this.mailtoLink.AutoSize = true;
            this.mailtoLink.BackColor = System.Drawing.Color.Transparent;
            this.mailtoLink.LinkArea = new System.Windows.Forms.LinkArea(18, 37);
            this.mailtoLink.Location = new System.Drawing.Point(368, 46);
            this.mailtoLink.Name = "mailtoLink";
            this.mailtoLink.Size = new System.Drawing.Size(222, 17);
            this.mailtoLink.TabIndex = 15;
            this.mailtoLink.TabStop = true;
            this.mailtoLink.Text = "Служба поддержки: chumak@yaroslavl.ru";
            this.mailtoLink.UseCompatibleTextRendering = true;
            this.mailtoLink.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.mailtoLink_LinkClicked);
            // 
            // label1
            // 
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.label1.Location = new System.Drawing.Point(329, 56);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(312, 46);
            this.label1.TabIndex = 18;
            this.label1.Text = "Программа для расчета заработной платы рабочим и служащим в любых ее формах в\r\nлю" +
                "бых регионах России.";
            this.label1.TextAlign = System.Drawing.ContentAlignment.TopRight;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.label2.Location = new System.Drawing.Point(428, 24);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(213, 13);
            this.label2.TabIndex = 17;
            this.label2.Text = "Для windows 98/ME/2000/XP/2003/Vista";
            this.label2.TextAlign = System.Drawing.ContentAlignment.TopRight;
            // 
            // site2Link
            // 
            this.site2Link.AutoSize = true;
            this.site2Link.BackColor = System.Drawing.Color.Transparent;
            this.site2Link.Location = new System.Drawing.Point(473, 32);
            this.site2Link.Name = "site2Link";
            this.site2Link.Size = new System.Drawing.Size(125, 13);
            this.site2Link.TabIndex = 14;
            this.site2Link.TabStop = true;
            this.site2Link.Text = "http://www.acot-centr.ru";
            this.site2Link.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.site2Link_LinkClicked);
            // 
            // siteLink
            // 
            this.siteLink.AutoSize = true;
            this.siteLink.BackColor = System.Drawing.Color.Transparent;
            this.siteLink.LinkArea = new System.Windows.Forms.LinkArea(18, 45);
            this.siteLink.Location = new System.Drawing.Point(367, 17);
            this.siteLink.Name = "siteLink";
            this.siteLink.Size = new System.Drawing.Size(270, 17);
            this.siteLink.TabIndex = 13;
            this.siteLink.TabStop = true;
            this.siteLink.Text = "Официальный сайт: http://www.chumak.yaroslavl.ru";
            this.siteLink.UseCompatibleTextRendering = true;
            this.siteLink.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.siteLink_LinkClicked);
            // 
            // seeLicenseLinkLabel
            // 
            this.seeLicenseLinkLabel.AutoSize = true;
            this.seeLicenseLinkLabel.BackColor = System.Drawing.Color.Transparent;
            this.seeLicenseLinkLabel.LinkArea = new System.Windows.Forms.LinkArea(0, 27);
            this.seeLicenseLinkLabel.Location = new System.Drawing.Point(470, 69);
            this.seeLicenseLinkLabel.Name = "seeLicenseLinkLabel";
            this.seeLicenseLinkLabel.Size = new System.Drawing.Size(160, 13);
            this.seeLicenseLinkLabel.TabIndex = 12;
            this.seeLicenseLinkLabel.TabStop = true;
            this.seeLicenseLinkLabel.Text = "Свидетельство о регистрации";
            this.seeLicenseLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.seeLicenseLinkLabel_LinkClicked);
            // 
            // label4
            // 
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Location = new System.Drawing.Point(182, 46);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(194, 67);
            this.label4.TabIndex = 6;
            this.label4.Text = "8-4855-22-61-28\r\n+7 915 986 85 62\r\ne-mail: acotwin@gmail.com";
            // 
            // label3
            // 
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Location = new System.Drawing.Point(182, 32);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(179, 13);
            this.label3.TabIndex = 6;
            this.label3.Text = "Киселев Сергей Владимирович";
            // 
            // versionLabel
            // 
            this.versionLabel.BackColor = System.Drawing.Color.Transparent;
            this.versionLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.versionLabel.Location = new System.Drawing.Point(439, 9);
            this.versionLabel.Name = "versionLabel";
            this.versionLabel.Size = new System.Drawing.Size(202, 12);
            this.versionLabel.TabIndex = 16;
            this.versionLabel.Text = "ACOT версия 1.0 сборка 0138";
            this.versionLabel.TextAlign = System.Drawing.ContentAlignment.TopRight;
            // 
            // label6
            // 
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label6.Location = new System.Drawing.Point(7, 16);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(169, 13);
            this.label6.TabIndex = 6;
            this.label6.Text = "разработка ACOT:";
            // 
            // label5
            // 
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label5.Location = new System.Drawing.Point(182, 16);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(182, 13);
            this.label5.TabIndex = 6;
            this.label5.Text = "разработка ACOTwin:";
            // 
            // developerLabel1
            // 
            this.developerLabel1.BackColor = System.Drawing.Color.Transparent;
            this.developerLabel1.Location = new System.Drawing.Point(6, 32);
            this.developerLabel1.Name = "developerLabel1";
            this.developerLabel1.Size = new System.Drawing.Size(150, 66);
            this.developerLabel1.TabIndex = 6;
            this.developerLabel1.Text = "Чумак Сергей Николаевич\r\n8-4855-21-16-90\r\n8-4855-28-12-12 (тел/факс)\r\n+7920101077" +
                "7\r\ne-mail: chumak@yaroslavl.ru";
            // 
            // groupBox1
            // 
            this.groupBox1.BackColor = System.Drawing.Color.Transparent;
            this.groupBox1.Controls.Add(this.mailtoLink);
            this.groupBox1.Controls.Add(this.site2Link);
            this.groupBox1.Controls.Add(this.siteLink);
            this.groupBox1.Controls.Add(this.seeLicenseLinkLabel);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.developerLabel1);
            this.groupBox1.Location = new System.Drawing.Point(8, 132);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(635, 105);
            this.groupBox1.TabIndex = 15;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Контактная информация";
            // 
            // LayoutView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::ACOT.AboutModule.Properties.Resources.About2;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.versionLabel);
            this.Controls.Add(this.groupBox1);
            this.Name = "LayoutView";
            this.Size = new System.Drawing.Size(650, 246);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.LinkLabel mailtoLink;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.LinkLabel site2Link;
        private System.Windows.Forms.LinkLabel siteLink;
        private System.Windows.Forms.LinkLabel seeLicenseLinkLabel;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        internal System.Windows.Forms.Label versionLabel;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label developerLabel1;
        private System.Windows.Forms.GroupBox groupBox1;
    }
}
