//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Foundational Module" recipe.
//
// The Module class derives from the CAB base class ModuleInit and it will be instantiated
// when the module is loaded by the CAB infrastructure.
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-020-How_to_Create_a_Business_Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using Microsoft.Practices.CompositeUI;
using Microsoft.Practices.CompositeUI.Services;
using Microsoft.Practices.ObjectBuilder;
using ACOT.AboutModule.Constants;
using Microsoft.Practices.CompositeUI.EventBroker;
using ACOT.Infrastructure.Interface;
using ACOT.Infrastructure.Interface.Services;
using System;

namespace ACOT.AboutModule
{
    public class Module : ModuleInit
    {
        private WorkItem _rootWorkItem;
        private LayoutView workItem;

        [InjectionConstructor]
        public Module([ServiceDependency] WorkItem rootWorkItem)
        {
            _rootWorkItem = rootWorkItem;
        }

        public override void Load()
        {
            base.Load();

            // NOTE: 
            // The layout view in this module defines the layout of the shell. To do this, it
            // loads its view into a shell Workspace named "LayoutWorkspace". If the shell does 
            // not contain a Workspace with this name, the module will throw a ModuleLoadException exception. 
            // 
            // If you see this exception, you can modify the ShowLayoutView method to use a Workspace 
            // name available in shell, or change the name of a Workspace in the shell to "LayoutWorkspace".
            //ShowLayoutView();
        }

        private void ShowLayoutView()
        {
            if (_rootWorkItem.Workspaces.Contains(WorkspaceNames.LayoutWorkspace))
            {
                LayoutView layout = _rootWorkItem.Items.AddNew<LayoutView>();
                _rootWorkItem.Workspaces[WorkspaceNames.LayoutWorkspace].Show(layout);
            }
            else
                throw new ModuleLoadException("LayoutWorkpsace not found");
        }

        [EventSubscription(ACOT.Infrastructure.Interface.Constants.EventTopicNames.AboutDlgShow, Thread = ThreadOption.UserInterface)]
        public void AboutBoxShow(object sender, EventArgs<string> e)
        {
            const string workItemID = "AboutBox";
            if (_rootWorkItem.Items.Contains(workItemID))
                workItem = (LayoutView)_rootWorkItem.Items[workItemID];
            else
                workItem = _rootWorkItem.Items.AddNew<LayoutView>(workItemID);                       
            try
            {
                IContextService context = _rootWorkItem.Services.Get<IContextService>();
                workItem.VersionLabel.Text = context.version;                
                _rootWorkItem.Workspaces[WorkspaceNames.ModalWindows].Show(workItem);
            }
            catch (Exception ex)
            {
                System.Windows.Forms.MessageBox.Show(ex.Message);
            }
        }       
    }
}
