//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Foundational Module" recipe.
//
// The LayoutView usercontrol defines a layout decoupled from the shell. 
// It provides a left and right workspace, menu bar, tool bar and status bar.
// These ui elements are added as extension sites.
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-290-Automation%20Add%20Foundational%20Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.Exchange1CModule
{
    partial class Step2View
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this._btnSelectFile = new System.Windows.Forms.Button();
            this._filename = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this._openFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.SuspendLayout();
            // 
            // _btnSelectFile
            // 
            this._btnSelectFile.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this._btnSelectFile.Location = new System.Drawing.Point(338, 23);
            this._btnSelectFile.Name = "_btnSelectFile";
            this._btnSelectFile.Size = new System.Drawing.Size(21, 20);
            this._btnSelectFile.TabIndex = 7;
            this._btnSelectFile.UseVisualStyleBackColor = true;
            // 
            // _filename
            // 
            this._filename.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._filename.Location = new System.Drawing.Point(3, 23);
            this._filename.Name = "_filename";
            this._filename.Size = new System.Drawing.Size(329, 20);
            this._filename.TabIndex = 6;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label5.ForeColor = System.Drawing.SystemColors.InfoText;
            this.label5.Location = new System.Drawing.Point(3, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(249, 20);
            this.label5.TabIndex = 5;
            this.label5.Text = "Файл для хранения данных:";
            // 
            // Step2View
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._btnSelectFile);
            this.Controls.Add(this._filename);
            this.Controls.Add(this.label5);
            this.Name = "Step2View";
            this.Size = new System.Drawing.Size(384, 81);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button _btnSelectFile;
        private System.Windows.Forms.TextBox _filename;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.OpenFileDialog _openFileDialog;
    }
}
