//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Foundational Module" recipe.
//
// The LayoutView usercontrol defines a layout decoupled from the shell. 
// It provides a left and right workspace, menu bar, tool bar and status bar.
// These ui elements are added as extension sites.
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-290-Automation%20Add%20Foundational%20Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Text;
using System.Windows.Forms;
using ACOT.Exchange1CModule.Constants;
using Microsoft.Practices.ObjectBuilder;
using Microsoft.Practices.CompositeUI.SmartParts;
using ACOT.Infrastructure.Interface;
using ACOT.Infrastructure.Interface.Constants;

namespace ACOT.Exchange1CModule          
{
    public partial class Step1View : UserControl
    {
        private Step1Presenter _presenter; 

        /// <summary>
        /// Initializes a new instance of the <see cref="T:LayoutView"/> class.
        /// </summary>
        public Step1View()
        {
            InitializeComponent();
            //this._moduleWorkspace.Name = ACOT.Exchange1CModule.Constants.WorkspaceNames.Exchange1CModuleLayout;
        }

        /// <summary>
        /// Sets the presenter.
        /// </summary>
        /// <value>The presenter.</value>
        [CreateNew]
        public Step1Presenter Presenter
        {
            set
            {
                _presenter = value;
                _presenter.View = this;
            }
        }

        #region ISmartPartInfoProvider Members

        //ISmartPartInfo ISmartPartInfoProvider.GetSmartPartInfo(Type smartPartInfoType)
        //{
        //    ISmartPartInfo spi;
        //    if (smartPartInfoType.IsAssignableFrom(typeof(ACOT.Infrastructure.Interface.WindowSmartPartInfo)))
        //    {
        //        WindowSmartPartInfo LayoutView = new WindowSmartPartInfo();
        //        //LayoutView.Modal = true;
        //        //LayoutView.MinimizeBox = false;
        //        //LayoutView.MaximizeBox = false;
        //        LayoutView.ControlBox = true;

        //        //LayoutView.Keys[WindowWorkspaceSetting.FormBorderStyle] = FormBorderStyle.FixedDialog;
        //        LayoutView.Keys[WindowWorkspaceSetting.FormShowIcon] = false;
        //        //LayoutView.Keys[WindowWorkspaceSetting.StartPosition] = FormStartPosition.CenterParent;
        //        LayoutView.Keys[WindowWorkspaceSetting.AutoSize] = false;
        //        LayoutView.Keys[WindowWorkspaceSetting.KeyPreview] = true;

        //        LayoutView.Width = 700;
        //        LayoutView.Height = 400;

        //        spi = LayoutView;
        //    }
        //    else
        //    {
        //        spi = Activator.CreateInstance(smartPartInfoType) as ISmartPartInfo;
        //    }

        //    //spi.Description = Properties.Resources.FindCustomerResultsViewDescription;
        //    //spi.Title = "”ниверсальный обмен данными в формате XML (2.0)";
            

        //    return spi;
        //}

        #endregion

 

    }
}
