//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Foundational Module" recipe.
//
// The LayoutView usercontrol defines a layout decoupled from the shell. 
// It provides a left and right workspace, menu bar, tool bar and status bar.
// These ui elements are added as extension sites.
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-290-Automation%20Add%20Foundational%20Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.Exchange1CModule
{
    partial class LayoutView
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tabbedWorkspace1 = new Microsoft.Practices.CompositeUI.WinForms.TabWorkspace();
            this.tab = new System.Windows.Forms.TabPage();
            this.tabAccounts = new System.Windows.Forms.TabPage();
            this.btnFinish = new System.Windows.Forms.Button();
            this.btnNext = new System.Windows.Forms.Button();
            this.btnPrev = new System.Windows.Forms.Button();
            this.step1View1 = new ACOT.Exchange1CModule.Step1View();
            this.step2View1 = new ACOT.Exchange1CModule.Step2View();
            this.tabbedWorkspace1.SuspendLayout();
            this.tab.SuspendLayout();
            this.tabAccounts.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabbedWorkspace1
            // 
            this.tabbedWorkspace1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.tabbedWorkspace1.Controls.Add(this.tab);
            this.tabbedWorkspace1.Controls.Add(this.tabAccounts);
            this.tabbedWorkspace1.Location = new System.Drawing.Point(3, 3);
            this.tabbedWorkspace1.Name = "tabbedWorkspace1";
            this.tabbedWorkspace1.SelectedIndex = 0;
            this.tabbedWorkspace1.Size = new System.Drawing.Size(620, 212);
            this.tabbedWorkspace1.TabIndex = 6;
            // 
            // tab
            // 
            this.tab.AutoScroll = true;
            this.tab.BackColor = System.Drawing.Color.White;
            this.tab.Controls.Add(this.step1View1);
            this.tab.Location = new System.Drawing.Point(4, 22);
            this.tab.Name = "tab";
            this.tab.Padding = new System.Windows.Forms.Padding(5);
            this.tab.Size = new System.Drawing.Size(612, 186);
            this.tab.TabIndex = 0;
            this.tab.Text = "Шаг 1";
            // 
            // tabAccounts
            // 
            this.tabAccounts.BackColor = System.Drawing.Color.White;
            this.tabAccounts.Controls.Add(this.step2View1);
            this.tabAccounts.Location = new System.Drawing.Point(4, 22);
            this.tabAccounts.Name = "tabAccounts";
            this.tabAccounts.Padding = new System.Windows.Forms.Padding(5);
            this.tabAccounts.Size = new System.Drawing.Size(655, 186);
            this.tabAccounts.TabIndex = 1;
            this.tabAccounts.Text = "Шаг2";
            // 
            // btnFinish
            // 
            this.btnFinish.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFinish.Location = new System.Drawing.Point(514, 221);
            this.btnFinish.Name = "btnFinish";
            this.btnFinish.Size = new System.Drawing.Size(85, 25);
            this.btnFinish.TabIndex = 7;
            this.btnFinish.Text = "Выгрузить";
            this.btnFinish.UseVisualStyleBackColor = true;
            // 
            // btnNext
            // 
            this.btnNext.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNext.Location = new System.Drawing.Point(423, 221);
            this.btnNext.Name = "btnNext";
            this.btnNext.Size = new System.Drawing.Size(85, 25);
            this.btnNext.TabIndex = 8;
            this.btnNext.Text = "Следующий";
            this.btnNext.UseVisualStyleBackColor = true;
            // 
            // btnPrev
            // 
            this.btnPrev.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnPrev.Location = new System.Drawing.Point(332, 221);
            this.btnPrev.Name = "btnPrev";
            this.btnPrev.Size = new System.Drawing.Size(85, 25);
            this.btnPrev.TabIndex = 9;
            this.btnPrev.Text = "Предыдущий";
            this.btnPrev.UseVisualStyleBackColor = true;
            // 
            // step1View1
            // 
            this.step1View1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.step1View1.Location = new System.Drawing.Point(5, 5);
            this.step1View1.Name = "step1View1";
            this.step1View1.Size = new System.Drawing.Size(602, 176);
            this.step1View1.TabIndex = 0;
            // 
            // step2View1
            // 
            this.step2View1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.step2View1.Location = new System.Drawing.Point(5, 5);
            this.step2View1.Name = "step2View1";
            this.step2View1.Size = new System.Drawing.Size(645, 176);
            this.step2View1.TabIndex = 0;
            // 
            // LayoutView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.btnPrev);
            this.Controls.Add(this.btnNext);
            this.Controls.Add(this.btnFinish);
            this.Controls.Add(this.tabbedWorkspace1);
            this.Name = "LayoutView";
            this.Size = new System.Drawing.Size(692, 256);
            this.tabbedWorkspace1.ResumeLayout(false);
            this.tab.ResumeLayout(false);
            this.tabAccounts.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Microsoft.Practices.CompositeUI.WinForms.TabWorkspace tabbedWorkspace1;
        private System.Windows.Forms.TabPage tab;
        private System.Windows.Forms.TabPage tabAccounts;
        private System.Windows.Forms.Button btnFinish;
        private System.Windows.Forms.Button btnNext;
        private System.Windows.Forms.Button btnPrev;
        private Step1View step1View1;
        private Step2View step2View1;
    }
}
