//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-210-Creating%20a%20Smart%20Client%20Solution.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.Infrastructure.Interface.Constants
{
    /// <summary>
    /// Constants for command names.
    /// </summary>
    public class CommandNames
    {
        public const string AcotExit = "AcotExit";
        public const string AboutBoxShow = "AboutBoxShow";
        public const string SettingsShow = "SettingsDlgShow";
        public const string SplashShow = "SplashDlgShow";

        public const string Exchange1CDlgShow = "Exchange1CDlgShow";

        public const string ChkAddrDlgShow = "ChkAddrDlgShow";

        //public const string InfoViewExeShow = "InfoViewExeShow";
        //public const string InfoViewResShow = "InfoViewResShow";
        //public const string InfoViewHlpShow = "InfoViewHlpShow";
        //public const string InfoViewCurShow = "InfoViewCurShow";
        //public const string InfoViewAllShow = "InfoViewAllShow";
        
    }
}
