//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-210-Creating%20a%20Smart%20Client%20Solution.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.Infrastructure.Interface.Constants
{
    /// <summary>
    /// Constants for modules names.
    /// </summary>
    public class ModuleNames
    {
        public const string AboutModule = "AboutModule.dll";

        public const string SettingsModule = "SettingsModule.dll";

        public const string InfoViewModule = "InfoViewModule.dll";

        public const string Exchange1CModule = "Exchange1CModule.dll";

        public const string TreeModule = "Infrastructure.Tree.dll";

        public const string ChkAddrModule = "ChkAddrModule.dll";

    }
}
