//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-210-Creating%20a%20Smart%20Client%20Solution.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.Infrastructure.Interface.Constants
{
    /// <summary>
    /// Constants for UI extension site names.
    /// </summary>
    public class UIExtensionSiteNames
    {
        /// <summary>
        /// The extension site for the main menu.
        /// </summary>
        public const string MainMenu = "MainMenu";

        /// <summary>
        /// The extension site for the main toolbar.
        /// </summary>
        public const string MainToolbar = "MainToolbar";

        /// <summary>
        /// The extension site for the main status bar.
        /// </summary>
        public const string MainStatus = "MainStatus";

        /// <summary>
        /// The extension site for the menu tree.
        /// </summary>
        public const string MainMenuTreeView = "MainMenuTreeView";

        /// <summary>
        /// The extension site for the main menu item "–¿«Õ€≈".
        /// </summary>
        public const string DifferentMenuItem = "00007";

        /// <summary>
        /// The extension site for the main menu item "–¿«Õ€≈".
        /// </summary>
        public const string InfoViewMenuItem = "00079";

        /// <summary>
        /// The extension site for the main menu item "”ÒÚ‡ÌÓ‚ÍË".
        /// </summary>
        public const string SettingsMenu = "SettingsMenu";
    }
}
