//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Foundational Module" recipe.
//
// The LayoutView usercontrol defines a layout decoupled from the shell. 
// It provides a left and right workspace, menu bar, tool bar and status bar.
// These ui elements are added as extension sites.
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/03-01-030-How_to_Create_a_Foundational_Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.Infrastructure.Module.Views
{
    partial class TreeMenuView
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TreeMenuView));
            this.imageList = new System.Windows.Forms.ImageList(this.components);
            this._treeView = new ACOT.Infrastructure.Controls.TreeViewAdvanced.TreeViewAdv();
            this._textNode = new ACOT.Infrastructure.Controls.TreeViewAdvanced.NodeControls.NodeTextBox();
            this._nodeStateIcon = new ACOT.Infrastructure.Controls.TreeViewAdvanced.NodeControls.NodeStateIcon();
            this.SuspendLayout();
            // 
            // imageList
            // 
            this.imageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList.ImageStream")));
            this.imageList.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList.Images.SetKeyName(0, "Folder.bmp");
            this.imageList.Images.SetKeyName(1, "Rule.bmp");
            // 
            // _treeView
            // 
            this._treeView.BackColor = System.Drawing.SystemColors.Window;
            this._treeView.Cursor = System.Windows.Forms.Cursors.Default;
            this._treeView.DefaultToolTipProvider = null;
            this._treeView.Dock = System.Windows.Forms.DockStyle.Fill;
            this._treeView.DragDropMarkColor = System.Drawing.Color.Black;
            this._treeView.FullRowSelect = true;
            this._treeView.LineColor = System.Drawing.SystemColors.ControlDark;
            this._treeView.Location = new System.Drawing.Point(0, 0);
            this._treeView.Model = null;
            this._treeView.Name = "_treeView";
            this._treeView.NodeControls.Add(this._nodeStateIcon);
            this._treeView.NodeControls.Add(this._textNode);
            this._treeView.SelectedNode = null;
            this._treeView.ShowNodeToolTips = true;
            this._treeView.Size = new System.Drawing.Size(150, 150);
            this._treeView.TabIndex = 0;
            this._treeView.Text = "treeView";
            this._treeView.DoubleClick += new System.EventHandler(this._treeView_DoubleClick);
            this._treeView.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this._treeView_KeyPress);
            this._treeView.KeyDown += new System.Windows.Forms.KeyEventHandler(this._treeView_KeyDown);
            // 
            // _textNode
            // 
            this._textNode.DataPropertyName = "Text";
            this._textNode.EditEnabled = false;
            this._textNode.IncrementalSearchEnabled = true;
            this._textNode.LeftMargin = 3;
            this._textNode.ParentColumn = null;
            // 
            // _nodeStateIcon
            // 
            this._nodeStateIcon.IncrementalSearchEnabled = true;
            this._nodeStateIcon.LeftMargin = 1;
            this._nodeStateIcon.ParentColumn = null;
            // 
            // TreeMenuView
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.AutoScroll = true;
            this.Controls.Add(this._treeView);
            this.Name = "TreeMenuView";
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ImageList imageList;
        private ACOT.Infrastructure.Controls.TreeViewAdvanced.TreeViewAdv _treeView;
        private ACOT.Infrastructure.Controls.TreeViewAdvanced.NodeControls.NodeTextBox _textNode;
        private ACOT.Infrastructure.Controls.TreeViewAdvanced.NodeControls.NodeStateIcon _nodeStateIcon;

    }
}
