//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// The FormShell class represent the main form of your application.
// 
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-210-Creating%20a%20Smart%20Client%20Solution.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.Infrastructure.Shell
{
    partial class ShellForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ShellForm));
            this._mainStatusStrip = new System.Windows.Forms.StatusStrip();
            this._statusLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this._mainToolStrip = new System.Windows.Forms.ToolStrip();
            this._mainMenuStrip = new System.Windows.Forms.MenuStrip();
            this._splitter = new ACOT.Infrastructure.Controls.XPanderControls.Splitter();
            this._treePanel = new ACOT.Infrastructure.Controls.XPanderControls.Panel();
            this._deckWorkspace = new Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace();
            this._mainStatusStrip.SuspendLayout();
            this._treePanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // _mainStatusStrip
            // 
            this._mainStatusStrip.AutoSize = false;
            this._mainStatusStrip.BackColor = System.Drawing.Color.IndianRed;
            this._mainStatusStrip.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this._mainStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._statusLabel});
            this._mainStatusStrip.Location = new System.Drawing.Point(0, 491);
            this._mainStatusStrip.Name = "_mainStatusStrip";
            this._mainStatusStrip.Size = new System.Drawing.Size(698, 25);
            this._mainStatusStrip.TabIndex = 9;
            this._mainStatusStrip.Text = "_mainStatusStrip";
            // 
            // _statusLabel
            // 
            this._statusLabel.AutoToolTip = true;
            this._statusLabel.Name = "_statusLabel";
            this._statusLabel.Size = new System.Drawing.Size(0, 20);
            // 
            // _mainToolStrip
            // 
            this._mainToolStrip.Location = new System.Drawing.Point(0, 24);
            this._mainToolStrip.Name = "_mainToolStrip";
            this._mainToolStrip.Size = new System.Drawing.Size(698, 25);
            this._mainToolStrip.TabIndex = 8;
            this._mainToolStrip.Text = "_mainToolStrip";
            this._mainToolStrip.Visible = false;
            // 
            // _mainMenuStrip
            // 
            this._mainMenuStrip.Location = new System.Drawing.Point(0, 0);
            this._mainMenuStrip.Name = "_mainMenuStrip";
            this._mainMenuStrip.ShowItemToolTips = true;
            this._mainMenuStrip.Size = new System.Drawing.Size(698, 24);
            this._mainMenuStrip.TabIndex = 7;
            this._mainMenuStrip.Text = "_mainMenuStrip";
            // 
            // _splitter
            // 
            this._splitter.Location = new System.Drawing.Point(256, 24);
            this._splitter.Name = "_splitter";
            this._splitter.Size = new System.Drawing.Size(3, 467);
            this._splitter.TabIndex = 13;
            this._splitter.TabStop = false;
            // 
            // _treePanel
            // 
            this._treePanel.BackColor = System.Drawing.Color.Transparent;
            this._treePanel.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(229)))), ((int)(((byte)(229)))));
            this._treePanel.CaptionFont = new System.Drawing.Font("Trebuchet MS", 10.5F, System.Drawing.FontStyle.Bold);
            this._treePanel.CaptionForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this._treePanel.CloseIconForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this._treePanel.CollapsedCaptionForeColor = System.Drawing.SystemColors.ControlText;
            this._treePanel.ColorCaptionGradientBegin = System.Drawing.Color.FromArgb(((int)(((byte)(233)))), ((int)(((byte)(233)))), ((int)(((byte)(233)))));
            this._treePanel.ColorCaptionGradientEnd = System.Drawing.SystemColors.ButtonShadow;
            this._treePanel.ColorCaptionGradientMiddle = System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227)))));
            this._treePanel.ColorContentPanelGradientBegin = System.Drawing.Color.Empty;
            this._treePanel.ColorContentPanelGradientEnd = System.Drawing.Color.Empty;
            this._treePanel.Controls.Add(this._deckWorkspace);
            this._treePanel.DataBindings.Add(new System.Windows.Forms.Binding("Size", global::ACOT.Infrastructure.Shell.Properties.Settings.Default, "LeftPanelSize", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._treePanel.DataBindings.Add(new System.Windows.Forms.Binding("Visible", global::ACOT.Infrastructure.Shell.Properties.Settings.Default, "LeftPanelVisible", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged));
            this._treePanel.Dock = System.Windows.Forms.DockStyle.Left;
            this._treePanel.ForeColor = System.Drawing.SystemColors.ControlText;
            this._treePanel.Image = null;
            this._treePanel.InnerBorderColor = System.Drawing.Color.White;
            this._treePanel.LinearGradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this._treePanel.Location = new System.Drawing.Point(0, 24);
            this._treePanel.Name = "_treePanel";
            this._treePanel.PanelStyle = ACOT.Infrastructure.Controls.XPanderControls.PanelStyle.Default;
            this._treePanel.ShowCloseIcon = true;
            this._treePanel.ShowExpandIcon = true;
            this._treePanel.ShowTransparentBackground = false;
            this._treePanel.Size = global::ACOT.Infrastructure.Shell.Properties.Settings.Default.LeftPanelSize;
            this._treePanel.TabIndex = 11;
            this._treePanel.Text = "Дерево меню";
            this._treePanel.Visible = global::ACOT.Infrastructure.Shell.Properties.Settings.Default.LeftPanelVisible;
            this._treePanel.CloseClick += new System.EventHandler<System.EventArgs>(this._treePanel_CloseClick);
            // 
            // _deckWorkspace
            // 
            this._deckWorkspace.Dock = System.Windows.Forms.DockStyle.Fill;
            this._deckWorkspace.Location = new System.Drawing.Point(1, 26);
            this._deckWorkspace.Name = "_deckWorkspace";
            this._deckWorkspace.Size = new System.Drawing.Size(254, 440);
            this._deckWorkspace.TabIndex = 0;
            this._deckWorkspace.Text = "deckWorkspace1";
            // 
            // ShellForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.ClientSize = new System.Drawing.Size(698, 516);
            this.Controls.Add(this._splitter);
            this.Controls.Add(this._treePanel);
            this.Controls.Add(this._mainStatusStrip);
            this.Controls.Add(this._mainToolStrip);
            this.Controls.Add(this._mainMenuStrip);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.IsMdiContainer = true;
            this.Name = "ShellForm";
            this.Text = "Выберите организацию";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this._mainStatusStrip.ResumeLayout(false);
            this._mainStatusStrip.PerformLayout();
            this._treePanel.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.StatusStrip _mainStatusStrip;
        private System.Windows.Forms.ToolStripStatusLabel _statusLabel;
        private System.Windows.Forms.ToolStrip _mainToolStrip;
        private System.Windows.Forms.MenuStrip _mainMenuStrip;
        private ACOT.Infrastructure.Controls.XPanderControls.Panel _treePanel;
        public Microsoft.Practices.CompositeUI.WinForms.DeckWorkspace _deckWorkspace;
        private ACOT.Infrastructure.Controls.XPanderControls.Splitter _splitter;
    }
}
