//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-08-060-Add_Business_Module_Next_Steps.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.Infrastructure.Module.Constants
{
    /// <summary>
    /// Constants for command names.
    /// </summary>
    public class CommandNames : ACOT.Infrastructure.Interface.Constants.CommandNames
    {
        public const string СведенияОбОрганизации = "Сведения по &оpганизации";
        public const string ПроизводственныыйКалендарьВинд = "&Пpоизводственный календаpь в WINDOWS";
        public const string ПереходНаСледМесяцВклСдвиг = "&Пеpеход на следующий месяц, включая SDWIG";
        public const string СменаОрганизации = "Смена &организации";        
        public const string ПечатьPRNLST = "Печать &любых файлов (ls*,txt) -  PRNLST";
        public const string ПечатьPRNCARD = "Печать &наборов NK, NS, SN, LSN - PRNCARD";
        public const string ПреобразованиеФайловTXT2DBF = "&Преобразование файлов TXT в DBF";
        public const string ПоказатьCправку = "Показать справку";
        public const string ПечатьКнигДокументации = "Печать &книг документации";
        public const string ПросмотрИнфоОФайлахEXE = "Просмотр ДАТ и РАЗМЕРОВ программ EXE";
        public const string ПросмотрИнфоОФайлахRES = "Просмотр ДАТ и РАЗМЕРОВ наборов RES";
        public const string ПросмотрИнфоОФайлахHLP = "Просмотр ДАТ и РАЗМЕРОВ наборов hlp";
        public const string ПросмотрИнфоОФайлахORG = "Просмотр ДАТ и РАЗМЕРОВ наборов текущей организации";
        public const string ПросмотрИнфоОФайлахALL = "Просмотр ДАТ и РАЗМЕРОВ *.???";
        public const string УниверсальныйОбменXML = "Универсальный обмен данными XML";
    }
}
