//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Foundational Module" recipe.
//
// The LayoutView usercontrol defines a layout decoupled from the shell. 
// It provides a left and right workspace, menu bar, tool bar and status bar.
// These ui elements are added as extension sites.
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-290-Automation%20Add%20Foundational%20Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace ACOT.SettingsModule
{
    partial class LayoutView
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LayoutView));
            this.tabControl = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this._shellFontTextBox = new System.Windows.Forms.TextBox();
            this.bevelLine5 = new ACOT.Infrastructure.Controls.BevelLine.BevelLine.BevelLine();
            this.bevelLine4 = new ACOT.Infrastructure.Controls.BevelLine.BevelLine.BevelLine();
            this.bevelLine2 = new ACOT.Infrastructure.Controls.BevelLine.BevelLine.BevelLine();
            this.bevelLine3 = new ACOT.Infrastructure.Controls.BevelLine.BevelLine.BevelLine();
            this.bevelLine1 = new ACOT.Infrastructure.Controls.BevelLine.BevelLine.BevelLine();
            this._showTreeCheckBox = new System.Windows.Forms.CheckBox();
            this.selectFontBtn = new System.Windows.Forms.Button();
            this.selDesktopBtn = new System.Windows.Forms.Button();
            this.selAcotPathBtn = new System.Windows.Forms.Button();
            this._desktopTextBox = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this._acotFolderPathTextBox = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this._cancelBtn = new System.Windows.Forms.Button();
            this._oKbtn = new System.Windows.Forms.Button();
            this.folderBrowserDialog = new System.Windows.Forms.FolderBrowserDialog();
            this.fontDialog = new System.Windows.Forms.FontDialog();
            this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.tabControl.SuspendLayout();
            this.tabPage1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // tabControl
            // 
            this.tabControl.Controls.Add(this.tabPage1);
            this.tabControl.Location = new System.Drawing.Point(3, 4);
            this.tabControl.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.tabControl.Name = "tabControl";
            this.tabControl.SelectedIndex = 0;
            this.tabControl.Size = new System.Drawing.Size(350, 293);
            this.tabControl.TabIndex = 2;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.pictureBox1);
            this.tabPage1.Controls.Add(this._shellFontTextBox);
            this.tabPage1.Controls.Add(this.bevelLine5);
            this.tabPage1.Controls.Add(this.bevelLine4);
            this.tabPage1.Controls.Add(this.bevelLine2);
            this.tabPage1.Controls.Add(this.bevelLine3);
            this.tabPage1.Controls.Add(this.bevelLine1);
            this.tabPage1.Controls.Add(this._showTreeCheckBox);
            this.tabPage1.Controls.Add(this.selectFontBtn);
            this.tabPage1.Controls.Add(this.selDesktopBtn);
            this.tabPage1.Controls.Add(this.selAcotPathBtn);
            this.tabPage1.Controls.Add(this._desktopTextBox);
            this.tabPage1.Controls.Add(this.label2);
            this.tabPage1.Controls.Add(this._acotFolderPathTextBox);
            this.tabPage1.Controls.Add(this.label3);
            this.tabPage1.Controls.Add(this.label1);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.tabPage1.Size = new System.Drawing.Size(342, 267);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Вид";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.ErrorImage = null;
            this.pictureBox1.Image = global::ACOT.SettingsModule.Properties.Resources.Font4;
            this.pictureBox1.InitialImage = null;
            this.pictureBox1.Location = new System.Drawing.Point(19, 168);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(54, 54);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 17;
            this.pictureBox1.TabStop = false;
            // 
            // _shellFontTextBox
            // 
            this._shellFontTextBox.Location = new System.Drawing.Point(79, 185);
            this._shellFontTextBox.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this._shellFontTextBox.Name = "_shellFontTextBox";
            this._shellFontTextBox.ReadOnly = true;
            this._shellFontTextBox.Size = new System.Drawing.Size(133, 20);
            this._shellFontTextBox.TabIndex = 16;
            this._shellFontTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // bevelLine5
            // 
            this.bevelLine5.Angle = 90;
            this.bevelLine5.Location = new System.Drawing.Point(9, 233);
            this.bevelLine5.Name = "bevelLine5";
            this.bevelLine5.Size = new System.Drawing.Size(316, 2);
            this.bevelLine5.TabIndex = 15;
            // 
            // bevelLine4
            // 
            this.bevelLine4.Angle = 90;
            this.bevelLine4.Location = new System.Drawing.Point(0, 0);
            this.bevelLine4.Name = "bevelLine4";
            this.bevelLine4.Size = new System.Drawing.Size(75, 2);
            this.bevelLine4.TabIndex = 14;
            // 
            // bevelLine2
            // 
            this.bevelLine2.Angle = 90;
            this.bevelLine2.Blend = true;
            this.bevelLine2.Location = new System.Drawing.Point(132, 98);
            this.bevelLine2.Name = "bevelLine2";
            this.bevelLine2.Size = new System.Drawing.Size(193, 2);
            this.bevelLine2.TabIndex = 13;
            // 
            // bevelLine3
            // 
            this.bevelLine3.Angle = 90;
            this.bevelLine3.Blend = true;
            this.bevelLine3.Location = new System.Drawing.Point(117, 161);
            this.bevelLine3.Name = "bevelLine3";
            this.bevelLine3.Size = new System.Drawing.Size(208, 2);
            this.bevelLine3.TabIndex = 12;
            // 
            // bevelLine1
            // 
            this.bevelLine1.Angle = 90;
            this.bevelLine1.Blend = true;
            this.bevelLine1.Location = new System.Drawing.Point(87, 29);
            this.bevelLine1.Name = "bevelLine1";
            this.bevelLine1.Size = new System.Drawing.Size(238, 2);
            this.bevelLine1.TabIndex = 10;
            // 
            // _showTreeCheckBox
            // 
            this._showTreeCheckBox.AutoSize = true;
            this._showTreeCheckBox.Checked = true;
            this._showTreeCheckBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this._showTreeCheckBox.Location = new System.Drawing.Point(19, 242);
            this._showTreeCheckBox.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this._showTreeCheckBox.Name = "_showTreeCheckBox";
            this._showTreeCheckBox.Size = new System.Drawing.Size(159, 17);
            this._showTreeCheckBox.TabIndex = 9;
            this._showTreeCheckBox.Text = "Показывать дерево меню";
            this._showTreeCheckBox.UseVisualStyleBackColor = true;
            // 
            // selectFontBtn
            // 
            this.selectFontBtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.selectFontBtn.FlatAppearance.BorderSize = 0;
            this.selectFontBtn.Location = new System.Drawing.Point(218, 183);
            this.selectFontBtn.Name = "selectFontBtn";
            this.selectFontBtn.Size = new System.Drawing.Size(105, 23);
            this.selectFontBtn.TabIndex = 2;
            this.selectFontBtn.Text = "Выбрать шрифт...";
            this.selectFontBtn.UseVisualStyleBackColor = true;
            this.selectFontBtn.Click += new System.EventHandler(this.selectFontBtn_Click);
            // 
            // selDesktopBtn
            // 
            this.selDesktopBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("selDesktopBtn.BackgroundImage")));
            this.selDesktopBtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.selDesktopBtn.FlatAppearance.BorderSize = 0;
            this.selDesktopBtn.Location = new System.Drawing.Point(305, 46);
            this.selDesktopBtn.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.selDesktopBtn.Name = "selDesktopBtn";
            this.selDesktopBtn.Size = new System.Drawing.Size(20, 20);
            this.selDesktopBtn.TabIndex = 4;
            this.selDesktopBtn.Text = "...";
            this.selDesktopBtn.UseVisualStyleBackColor = true;
            this.selDesktopBtn.Click += new System.EventHandler(this.selDesktopBtn_Click);
            // 
            // selAcotPathBtn
            // 
            this.selAcotPathBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("selAcotPathBtn.BackgroundImage")));
            this.selAcotPathBtn.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.selAcotPathBtn.FlatAppearance.BorderSize = 0;
            this.selAcotPathBtn.Location = new System.Drawing.Point(305, 107);
            this.selAcotPathBtn.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.selAcotPathBtn.Name = "selAcotPathBtn";
            this.selAcotPathBtn.Size = new System.Drawing.Size(20, 20);
            this.selAcotPathBtn.TabIndex = 6;
            this.selAcotPathBtn.Text = "...";
            this.selAcotPathBtn.UseVisualStyleBackColor = true;
            this.selAcotPathBtn.Click += new System.EventHandler(this.selAcotPathBtn_Click);
            // 
            // _desktopTextBox
            // 
            this._desktopTextBox.Location = new System.Drawing.Point(19, 46);
            this._desktopTextBox.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this._desktopTextBox.Name = "_desktopTextBox";
            this._desktopTextBox.Size = new System.Drawing.Size(276, 20);
            this._desktopTextBox.TabIndex = 3;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(6, 20);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(75, 13);
            this.label2.TabIndex = 6;
            this.label2.Text = "Рабочий стол";
            // 
            // _acotFolderPathTextBox
            // 
            this._acotFolderPathTextBox.Location = new System.Drawing.Point(19, 107);
            this._acotFolderPathTextBox.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this._acotFolderPathTextBox.Name = "_acotFolderPathTextBox";
            this._acotFolderPathTextBox.Size = new System.Drawing.Size(276, 20);
            this._acotFolderPathTextBox.TabIndex = 5;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(6, 89);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(120, 13);
            this.label3.TabIndex = 6;
            this.label3.Text = "Путь к каталогу АСОТ";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(6, 152);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(105, 13);
            this.label1.TabIndex = 8;
            this.label1.Text = "Шрифт интерфейса";
            // 
            // _cancelBtn
            // 
            this._cancelBtn.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._cancelBtn.Location = new System.Drawing.Point(257, 305);
            this._cancelBtn.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this._cancelBtn.Name = "_cancelBtn";
            this._cancelBtn.Size = new System.Drawing.Size(87, 23);
            this._cancelBtn.TabIndex = 4;
            this._cancelBtn.Text = "Отмена";
            this._cancelBtn.UseVisualStyleBackColor = true;
            this._cancelBtn.Click += new System.EventHandler(this._cancelBtn_Click);
            // 
            // _oKbtn
            // 
            this._oKbtn.DialogResult = System.Windows.Forms.DialogResult.OK;
            this._oKbtn.Location = new System.Drawing.Point(164, 305);
            this._oKbtn.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this._oKbtn.Name = "_oKbtn";
            this._oKbtn.Size = new System.Drawing.Size(87, 23);
            this._oKbtn.TabIndex = 3;
            this._oKbtn.Text = "Сохранить";
            this._oKbtn.UseVisualStyleBackColor = true;
            this._oKbtn.Click += new System.EventHandler(this._oKbtn_Click);
            // 
            // folderBrowserDialog
            // 
            this.folderBrowserDialog.RootFolder = System.Environment.SpecialFolder.MyComputer;
            // 
            // fontDialog
            // 
            this.fontDialog.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.fontDialog.ShowEffects = false;
            // 
            // openFileDialog
            // 
            this.openFileDialog.FileName = "openFileDialog";
            // 
            // LayoutView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._cancelBtn);
            this.Controls.Add(this._oKbtn);
            this.Controls.Add(this.tabControl);
            this.Name = "LayoutView";
            this.Size = new System.Drawing.Size(360, 337);
            this.tabControl.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.CheckBox _showTreeCheckBox;
        private System.Windows.Forms.Button selectFontBtn;
        private System.Windows.Forms.Button selDesktopBtn;
        private System.Windows.Forms.Button selAcotPathBtn;
        private System.Windows.Forms.TextBox _desktopTextBox;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox _acotFolderPathTextBox;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button _cancelBtn;
        private System.Windows.Forms.Button _oKbtn;
        private System.Windows.Forms.FolderBrowserDialog folderBrowserDialog;
        private System.Windows.Forms.FontDialog fontDialog;
        private System.Windows.Forms.OpenFileDialog openFileDialog;
        private System.Windows.Forms.Label label1;
        private ACOT.Infrastructure.Controls.BevelLine.BevelLine.BevelLine bevelLine1;
        private ACOT.Infrastructure.Controls.BevelLine.BevelLine.BevelLine bevelLine2;
        private ACOT.Infrastructure.Controls.BevelLine.BevelLine.BevelLine bevelLine3;
        private ACOT.Infrastructure.Controls.BevelLine.BevelLine.BevelLine bevelLine5;
        private ACOT.Infrastructure.Controls.BevelLine.BevelLine.BevelLine bevelLine4;
        private System.Windows.Forms.TextBox _shellFontTextBox;
        private System.Windows.Forms.PictureBox pictureBox1;

    }
}
